version: "3.8"

services:
  tgwebapp:
    image: ghcr.io/korjavin/arithproblems:cb482bf596df939d1cbf660539c46c15de76a990
    container_name: arithproblems
    networks:
      - vaultwarden_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arithproblems.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.arithproblems.entrypoints=websecure"
      - "traefik.http.routers.arithproblems.tls.certresolver=myresolver"

    restart: unless-stopped

networks:
  vaultwarden_default:
    external: true
